### ISSUE TITLE
params not sent when items array is empty

### ISSUE THREAD

**Issue by olimart** [KaneCohen/tokenfield#26]
Hi and thanks for the library.

I'm having an issue when the array of items is empty. It works fine when I add items and submit form. However when I edit and remove items it seems that no params is sent to the server, where I'm expecting to receive an empty array. Please advise.

I'm overriding the default `itemName` if this helps.

**Comment by KaneCohen** [comment]
I'm assuming you submit form via normal HTTP request, not an AJAX request?

Your server is not receiving any data because there's no items in the tokenfield and therefore no corresponding HTML elements which would store the data.

Here's what an item HTML element looks like:
```html
<li class="tokenfield-set-item">
      <span class="item-label">ITEM LABEL</span>
      <a href="#" class="item-remove" tabindex="-1">×</a>
      <input class="item-input" type="hidden" name="items[]" value="ITEM_VALUE">
</li>
```

Not that it has an `<input>` element with `items[]` name which says to your form that you have certain data.

Thing is - HTML forms the way they work simply can not send an empty array to you, for more details on that you can check [here](https://stackoverflow.com/questions/32913127/how-to-submit-empty-array-from-html-form-post-to-php).

As a possible solution you could add a hidden input element where you assign same name as you use in the tokenfield and set value to be empty:

```html
<input type="hidden" name="itemName" value="" />
```

**Comment by olimart** [comment]
> I'm assuming you submit form via normal HTTP request, not an AJAX request?

Indeed

The hidden field with the same name and an empty value seems to do the trick. However, since I have 4-5 Tokenfield on my form it adds "useless" input elements. Will refactor later.

Thanks a lot for your help.
