### ISSUE TITLE
Is there a way to cancel selected suggestion?

### ISSUE THREAD

**Issue by simsim0709** [KaneCohen/tokenfield#4]
Hello, 

I was wondering if I can cancel selected suggestion? 

For example, if I have follow settings.

```
const tf = new Tokenfield({
      el: tagInputRef,
      items: [{name: 'sampletag'}, {name: 'samplesource'}],
      itemValue: '_id',
    });

```
And, I want to add new token "sample", but I can't really do that. "sampletag" is always added when I press enter or tab key. 

Is there any way I can do it?

**Comment by KaneCohen** [comment]
OK, I see the problem. Happens when you want to create new tag with some input which has a match in suggester. I'll need to add small patch which would allow user to unselect suggested items by hitting "UP" or "DOWN" arrow key. DO you think that would be sufficient?

Or maybe you have an idea as to how it should behave?

**Comment by KaneCohen** [comment]
Pushed updated version `v0.3.5` where if you have `newItems` set to `true` (default is `true`) then it would allow to deselect items in suggestions by using up/down arrows on the keyboard. Plus, first item is not selected by default.
