### ISSUE TITLE
Potential improvement and a question about trigger input field

### ISSUE THREAD

**Issue by PierreChls** [KaneCohen/tokenfield#5]
To begin, congralutations for your work, your lib is very cool and very easy to use. 👍🏻

### Potential improvements

It would be great to add keys options on your Tokenfield init. It would allow to customise our key event and token delimiter. We could delimite token with space, slash... and not only the enter key.

### Trigger input field

I use a virtual keyboard for my app and I would trigger an "*enter*" event when a button is triggered. 

- I initialized my input like this 

```javascript
<input id="e-mail-input" placeholder="Add your e-mails friend" />
```

- And I initialized my Tokenfield like this : 

```javascript
const tokenfield = new Tokenfield({
    el: document.querySelector('#e-mail-input'),
    maxItems: 4
})
```

But when I add a keypress listener, there are any events...

```javascript
$('#e-mail-input').keypress(function(e) {
    if (e.which == 13) {
        console.log('enter key pressed')
    }
})
```

**Comment by KaneCohen** [comment]
Huh, GitHub finally decided to show issue instead of 404 page.

Thanks for filing the issue. I'll address matter of custom separators and event not propagating.

**Comment by KaneCohen** [comment]
#### Regarding missing events

You don't see any events because we that element which you attached tokenfield to `#e-mail-input` is not being used within the tokenfield. Tokenfield has its own internal `.tokenfield-input` typehead which is what accepts all the input events. If you want to catch input events you'll need to open your dev tools and find out what's the correct selector for input you're looking for.

This behavior is present because Tokenfield could be instantiated for any element in the page - not just `<input>`.

----

#### Regarding custom delimiters

Latest version of the library (v0.3.7 at this moment) has extra options parameter: `keys`.
This parameter accepts a hash (object) of values with keys mapped to various actions.

Default hash looks like this:

````js
keys: {
  8:   'delete',                 // Backspace
  27:  'esc',
  37:  'left',
  38:  'up',
  39:  'right',
  40:  'down',
  46:  'delete',
  9:   'delimiter',         // Tab
  13:  'delimiter',        // Enter
  108: 'delimiter'        // Numpad Enter
}
````

Please note keycodes with action `delimiter`. Any press key event which has code linked to `delimiter` action would produce result as if you've clicked on `enter` or `tab` key.

For example, often times you might want to use "comma" (`,`) as delimiter for your tokens. So, how do we add this key so it would behave as delimiter? Quite simple. We know that key code for comma key is 188. When setting up tokenfield code would look like following:

````js
const tokenfield = new Tokenfield({
    el: document.querySelector('#my-tokenfield'),
    keys: {
      188: 'delimiter' // Map comma to delimiter action
    }
});
````
